[tools]
rojo = { source = "rojo-rbx/rojo", version = "7.1" }
remodel = { source = "roblox-aurora/remodel", version = "0.9.1-cloud.1" }
wally = { source = "UpliftGames/wally", version = "0.3" }
selene = { source = "Kampfkarren/selene", version = "0.19" }
stylua = { source = "JohnnyMorganz/StyLua", version = "0.13" }
tarmac = { source = "jeparlefrancais/tarmac", version = "0.7" }