[package]
name = "shadow/formations"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[place]
shared-packages = "game.ReplicatedStorage.Packages"

[dependencies]
Knit = "sleitnick/knit@1.4.2"
Component = "sleitnick/component@2.4.5"
Signal = "sleitnick/signal@1.1.0"

Roact = "roblox/roact@1.4.2"
Rodux = "roblox/rodux@3.0.0"
RoduxHooks = "solarhorizon/rodux-hooks@0.2.0"
Hooks = "kampfkarren/roact-hooks@0.3.0"
Flipper = "reselim/flipper@2.0.0"
RoactFlipper = "reselim/roact-flipper@2.0.0"
RoactSpring = "chriscerie/roact-spring@1.0.0"

Llama = "shanebutt/llama@1.1.4"
t = "osyrisrblx/t@3.0.0"
Janitor = "howmanysmall/janitor@1.13.15"
Promise = "evaera/promise@4.0.0"